import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { News_Cycle } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Particles from "@/components/particles";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    
    <html lang="en" className="overflow-auto scrollbar-hide">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
    
      <body
      >
        <Particles
        className="absolute inset-0 -z-10 animate-fade-in overflow-auto scrollbar-hide"
        quantity={100}
      />
        <Navbar />
        
        <div className="overflow-auto scrollbar-hide">{children}</div>
        
      </body>
      
    </html>
    
    </>
  );
}
